"""update user table

Revision ID: 3e449952cfb9
Revises: 1baa32a71f37
Create Date: 2022-05-03 21:37:34.026798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e449952cfb9'
down_revision = '1baa32a71f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('interests', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('image_url', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_url')
    op.drop_column('users', 'interests')
    # ### end Alembic commands ###
