"""empty message

Revision ID: 624867365311
Revises: 
Create Date: 2022-09-06 12:26:04.079492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624867365311'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
