"""empty message

Revision ID: a0cd479f7476
Revises: 76b0b1fc865a
Create Date: 2022-09-06 12:15:32.671400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0cd479f7476'
down_revision = '76b0b1fc865a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_images_id', table_name='images')
    op.drop_table('images')
    op.drop_index('ix_interest_id', table_name='interest')
    op.drop_table('interest')
    op.add_column('users', sa.Column('firstname', sa.String(), server_default='user', nullable=False))
    op.add_column('users', sa.Column('lastname', sa.String(), server_default='user', nullable=False))
    op.add_column('users', sa.Column('othername', sa.String(), server_default='', nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(), server_default='', nullable=False))
    op.add_column('users', sa.Column('occupation', sa.String(), server_default='', nullable=False))
    op.add_column('users', sa.Column('income', sa.String(), server_default='', nullable=False))
    op.add_column('users', sa.Column('address', sa.String(), server_default='', nullable=False))
    op.add_column('users', sa.Column('state', sa.String(), server_default='', nullable=False))
    op.add_column('users', sa.Column('dob', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False))
    op.add_column('users', sa.Column('grant', sa.String(), server_default='', nullable=False))
    op.add_column('users', sa.Column('credit_score', sa.String(), server_default='', nullable=False))
    op.add_column('users', sa.Column('grant_reason', sa.String(), server_default='', nullable=False))
    op.add_column('users', sa.Column('image_url', sa.String(), nullable=False))
    op.drop_column('users', 'age')
    op.drop_column('users', 'username')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.VARCHAR(), server_default=sa.text("'male'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('username', sa.VARCHAR(), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('age', sa.VARCHAR(), server_default=sa.text("'age'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('users', 'image_url')
    op.drop_column('users', 'grant_reason')
    op.drop_column('users', 'credit_score')
    op.drop_column('users', 'grant')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'state')
    op.drop_column('users', 'address')
    op.drop_column('users', 'income')
    op.drop_column('users', 'occupation')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'othername')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    op.create_table('interest',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('interests', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2022-05-13 07:02:44.432861+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='interest_owner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='interest_pkey')
    )
    op.create_index('ix_interest_id', 'interest', ['id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2022-05-09 09:31:37.136724+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='images_owner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='images_pkey')
    )
    op.create_index('ix_images_id', 'images', ['id'], unique=False)
    # ### end Alembic commands ###
