"""update user table2

Revision ID: e1b5e57dd6d7
Revises: ea2acdce9c10
Create Date: 2022-05-03 22:37:55.855266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b5e57dd6d7'
down_revision = 'ea2acdce9c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
